apply plugin: 'com.android.application'

def releaseKeystorePropertiesFile = rootProject.file('release/keystore.properties')
def releaseKeystoreProperties = new Properties()
if (releaseKeystorePropertiesFile.exists()) {
    releaseKeystoreProperties.load(new FileInputStream(releaseKeystorePropertiesFile))
}

android {
    compileSdk = 36
    defaultConfig {
        applicationId = "io.github.kennethchoinfosec.haven"
        minSdk = 24
        targetSdk = 36
        versionCode = 8
        versionName = "0.1.4"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        if (!releaseKeystoreProperties.isEmpty()) {
            release {
                storeFile = rootProject.file("release/${releaseKeystoreProperties['storeFile']}")
                storePassword = releaseKeystoreProperties['storePassword']
                keyAlias = releaseKeystoreProperties['keyAlias']
                keyPassword = releaseKeystoreProperties['keyPassword']
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            if (!releaseKeystoreProperties.isEmpty()) {
                signingConfig = signingConfigs.release
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    lint {
        disable 'MissingTranslation', 'ExtraTranslation', 'GoogleAppIndexingWarning', 'InvalidFragmentVersionForActivityResult'
    }
    buildFeatures {
        aidl = true
    }
    namespace = 'io.github.kennethchoinfosec.haven'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.legacy:legacy-support-core-ui:1.0.0'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.14.0-beta01'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}
